version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
      - deploy:
          name: Deploy
          command: |
            npm run issues
            git add -A
            git commit -m "Automated issues creation: ${CIRCLE_SHA1}"
            git push

            npm run build

            git config --global user.email $GH_EMAIL
            git config --global user.name $CIRCLE_USERNAME
            git clone $TARGET_REPO_URL targetDirectory
            cd ./targetDirectory/
            rm -rf ./_next
            rm -rf ./assets
            rm -rf ./favicon
            rm -rf ./posts
            echo "deleting folders from $PWD"
            cd ..
            npm run export
            /bin/cp ./out/* ./targetDirectory/ -R -f
            cd ./targetDirectory/
            echo "commit in dir $PWD into $TARGET_REPO_URL repo"
            git add -A
            git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
            git push
