version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
      - deploy:
          name: Deploy
          command: |
            npm run build

            git config --global user.email $GH_EMAIL
            git config --global user.name $CIRCLE_USERNAME
            git clone $TARGET_REPO_URL targetDirectory
            sleep 1
            cd ./targetDirectory/
            rm -rf ./_next
            rm -rf ./assets
            rm -rf ./favicon
            rm -rf ./posts
            cd ..
            npm run export
            sleep 1
            yes | cp ./out/* ./targetDirectory/ -R -i -v
            cd ./targetDirectory/
            sleep 5
            git add -A
            git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
            git push origin $TARGET_BRANCH
